# Generated by Django 5.0.6 on 2024-07-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_remove_college_location_attendancerecord_week_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_type",
        ),
        migrations.RemoveField(
            model_name="course",
            name="doctor",
        ),
        migrations.AddField(
            model_name="course",
            name="practical_doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practical_courses",
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="theoretical_doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theoretical_courses",
                to="doctor.doctor",
            ),
            preserve_default=False,
        ),
    ]
