# Generated by Django 5.0.6 on 2024-07-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_remove_course_course_type_remove_course_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="practical_doctor",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practical_courses",
                to="doctor.doctor",
            ),
            preserve_default=False,
        ),
    ]
