# Generated by Django 5.0.6 on 2024-07-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0009_alter_course_practical_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="practical_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practical_courses",
                to="doctor.doctor",
            ),
        ),
    ]
