# Generated by Django 5.0.6 on 2024-07-05 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0010_alter_course_practical_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 5, 22, 30, 45, 90461, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
