# Generated by Django 5.0.6 on 2024-07-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0011_alter_enrollment_enrollment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
