# Generated by Django 5.0.6 on 2024-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0013_alter_attendancerecord_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="student_photos/"),
        ),
    ]
