# Generated by Django 5.0.6 on 2024-07-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0015_practicalcourses"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicalcourses",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
            ),
            preserve_default=False,
        ),
    ]
