# Generated by Django 5.0.6 on 2024-07-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0018_enrollment_practicalcourse_alter_enrollment_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="practicalCourse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.practicalcourses",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.course",
            ),
        ),
    ]
