# Generated by Django 5.0.6 on 2024-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0020_remove_enrollment_practicalcourse_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="percentage",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="attendancesummary",
            name="attended_classes",
        ),
        migrations.RemoveField(
            model_name="attendancesummary",
            name="total_classes",
        ),
        migrations.RemoveField(
            model_name="attendancesummary",
            name="week_number",
        ),
    ]
