# Generated by Django 5.0.6 on 2024-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0021_alter_attendancesummary_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="deprivation_threshold",
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name="college",
            name="warning_threshold",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
