# Generated by Django 5.0.6 on 2024-07-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0022_college_deprivation_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.college",
            ),
            preserve_default=False,
        ),
    ]
