# Generated by Django 5.0.6 on 2024-07-20 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0025_attendancerecord_is_late"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
