# Generated by Django 5.0.6 on 2024-07-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0026_alter_attendancerecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="is_late",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
